include("test_ambwarning.jl")
include("test_big_dtree.jl")
include("test_examples.jl")
include("test_julia_signature.jl")
include("test_named_nodes.jl")
include("test_show_dispatch.jl")
include("test_showpattern.jl")
